/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as WaterQualityRouteImport } from './routes/water-quality'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PollutionRouteImport } from './routes/pollution'
import { Route as EcologyRouteImport } from './routes/ecology'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterQualityRoute = WaterQualityRouteImport.update({
  id: '/water-quality',
  path: '/water-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PollutionRoute = PollutionRouteImport.update({
  id: '/pollution',
  path: '/pollution',
  getParentRoute: () => rootRouteImport,
} as any)
const EcologyRoute = EcologyRouteImport.update({
  id: '/ecology',
  path: '/ecology',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/devices': typeof DevicesRoute
  '/ecology': typeof EcologyRoute
  '/pollution': typeof PollutionRoute
  '/settings': typeof SettingsRoute
  '/water-quality': typeof WaterQualityRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/devices': typeof DevicesRoute
  '/ecology': typeof EcologyRoute
  '/pollution': typeof PollutionRoute
  '/settings': typeof SettingsRoute
  '/water-quality': typeof WaterQualityRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/devices': typeof DevicesRoute
  '/ecology': typeof EcologyRoute
  '/pollution': typeof PollutionRoute
  '/settings': typeof SettingsRoute
  '/water-quality': typeof WaterQualityRoute
  '/weather': typeof WeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/devices'
    | '/ecology'
    | '/pollution'
    | '/settings'
    | '/water-quality'
    | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/devices'
    | '/ecology'
    | '/pollution'
    | '/settings'
    | '/water-quality'
    | '/weather'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/devices'
    | '/ecology'
    | '/pollution'
    | '/settings'
    | '/water-quality'
    | '/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  DevicesRoute: typeof DevicesRoute
  EcologyRoute: typeof EcologyRoute
  PollutionRoute: typeof PollutionRoute
  SettingsRoute: typeof SettingsRoute
  WaterQualityRoute: typeof WaterQualityRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water-quality': {
      id: '/water-quality'
      path: '/water-quality'
      fullPath: '/water-quality'
      preLoaderRoute: typeof WaterQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pollution': {
      id: '/pollution'
      path: '/pollution'
      fullPath: '/pollution'
      preLoaderRoute: typeof PollutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecology': {
      id: '/ecology'
      path: '/ecology'
      fullPath: '/ecology'
      preLoaderRoute: typeof EcologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  DevicesRoute: DevicesRoute,
  EcologyRoute: EcologyRoute,
  PollutionRoute: PollutionRoute,
  SettingsRoute: SettingsRoute,
  WaterQualityRoute: WaterQualityRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
